export const ACTION_PLAN_COPY = {
  sectionTitle: "Plano de Ação",
  awaitingPlan: "Aguardando Plano de Ação",
  createPlan: "Criar Plano de Ação",
  emptyBody: "Defina ações corretivas com responsável e prazo.",
  addAction: "Adicionar ação",
  progress: (completed: number, total: number) => `${completed} de ${total} concluídas`,
  overdue: "Atrasada",
  start: "Iniciar",
  submit: "Concluir",
  submitTitle: "Concluir ação",
  submitSend: "Enviar",
  completionLabel: "Descrição da conclusão",
  evidenceLabel: "Evidências",
  evidenceOptional: "Opcional para esta prioridade",
  evidenceRequired: "Obrigatório para prioridade Alta ou Crítica",
  evidenceRequiredError: "Anexe ao menos uma evidência para esta prioridade.",
  approve: "Aprovar",
  approveConfirm: "Confirmar aprovação desta ação?",
  reject: "Rejeitar",
  rejectTitle: "Informe o motivo da rejeição.",
  rejectNoteLabel: "Motivo da rejeição",
  completePlan: "Concluir plano",
  completePlanConfirm: "Concluir o Plano de Ação? Todas as ações elegíveis foram encerradas.",
  completePlanSuccess: "Plano concluído — validação da ocorrência em versão futura",
  selfValidation: "Quem concluiu a ação não pode validá-la.",
  forbidden: "Você não tem permissão para esta ação.",
  conflict: "O estado da ação mudou. Atualize e tente novamente.",
  loading: "Carregando plano…",
  offline: "Sem conexão. Reconecte para alterar o Plano de Ação.",
  successCreate: "Plano de Ação criado.",
  successSubmit: "Ação enviada para validação.",
  successValidate: "Ação validada.",
  successReject: "Ação rejeitada — retornou para correção.",
  confirmCreateTitle: "Criar Plano de Ação",
  confirmCreateBody: "Criar Plano de Ação para esta interdição?",
  myActions: "Minhas ações",
  allActions: "Todas",
  titlePlaceholder: "O que precisa ser feito?",
  dueLabel: "Prazo",
  priorityLabel: "Prioridade",
  responsibleLabel: "Responsável",
  cancel: "Cancelar",
  confirm: "Confirmar",
  addEvidence: "Adicionar evidência",
  evidenceLimit: (count: number, max: number) => `${count}/${max} evidências`,
} as const;
