export const DASHBOARD_COPY = {
  attentionSectionTitle: "Minha atenção",
  operationalSectionTitle: "Situação operacional",
  recentSectionTitle: "Ocorrências recentes",
  recentViewAll: "Ver todas",
  recentEmpty: "Nenhuma paralisação recente.",
  hseApprovalCta: "Aprovação HSE",
  greetingFallback: "Olá",
  greetingWithName: (firstName: string) => `Olá, ${firstName}`,
  switchOrganization: "Trocar",
  offline: "Sem conexão. Os números abaixo podem estar desatualizados.",
  loadError: "Não foi possível carregar seus indicadores.",
  retry: "Tentar novamente",
  emptyPersonal: "Nenhuma pendência pessoal no momento.",
  emptyOperational: "Nenhum indicador operacional disponível no momento.",
} as const;
