// Supabase-generated types (packages/types/src/database.types.ts) must never
// be edited manually — see docs/engineering.md §17.16 and
// .cursor/rules/004-supabase.mdc. Re-exported here so apps consume the
// database schema exclusively through this package.
export type { Database, Json } from "./database.types";
export { PERMISSION_CODES, isPermissionCode } from "./permission-codes";
export type { PermissionCode } from "./permission-codes";

export {
  OCCURRENCE_DECISION_TYPES,
  OCCURRENCE_SEVERITIES,
  OCCURRENCE_STATUSES,
  OCCURRENCE_SYNC_STATES,
  isOccurrenceDecisionType,
  isOccurrenceSeverity,
  isOccurrenceStatus,
} from "./occurrence-status";
export type {
  OccurrenceDecisionType,
  OccurrenceSeverity,
  OccurrenceStatus,
  OccurrenceSyncState,
} from "./occurrence-status";

export type {
  OccurrenceDetails,
  OccurrenceListFilters,
  OccurrenceStatusHistoryEntry,
  OccurrenceSummary,
} from "./occurrence";

export {
  OCCURRENCE_ATTACHMENT_BUCKET,
  OCCURRENCE_ATTACHMENT_CAPTION_MAX_LENGTH,
  OCCURRENCE_ATTACHMENT_MAX_COUNT_PER_OCCURRENCE,
  OCCURRENCE_ATTACHMENT_MAX_FILE_SIZE_BYTES,
  OCCURRENCE_ATTACHMENT_MIME_TYPES,
  OCCURRENCE_ATTACHMENT_SIGNED_URL_TTL_SECONDS,
  OCCURRENCE_ATTACHMENT_TYPES,
  OCCURRENCE_ATTACHMENT_UPLOAD_STATUSES,
  isOccurrenceAttachmentMimeType,
  isOccurrenceAttachmentType,
  isOccurrenceAttachmentUploadStatus,
} from "./occurrence-attachment";
export type {
  OccurrenceAttachmentMimeType,
  OccurrenceAttachmentSignedUrlResult,
  OccurrenceAttachmentSummary,
  OccurrenceAttachmentType,
  OccurrenceAttachmentUploadStatus,
  PrepareOccurrenceAttachmentUploadResult,
} from "./occurrence-attachment";

export {
  PREVENTIVE_STOP_DEFAULT_STATUS,
  PREVENTIVE_STOP_LIST_FILTER_STATUSES,
  PREVENTIVE_STOP_STATUSES,
  PREVENTIVE_STOP_TITLE_MAX_LENGTH,
  isPreventiveStopStatus,
} from "./preventive-stop";
export type {
  OrganizationContractOption,
  OrganizationContractorOption,
  PreventiveStopListFilters,
  PreventiveStopStatus,
} from "./preventive-stop";

export {
  OCCURRENCE_COMMENT_EDIT_WINDOW_HOURS,
  OCCURRENCE_COMMENT_MAX_LENGTH,
  OCCURRENCE_COMMENT_TYPES,
  USER_CREATABLE_COMMENT_TYPES,
  isOccurrenceCommentType,
  isUserCreatableCommentType,
} from "./occurrence-comment";
export type {
  CreateOccurrenceCommentResult,
  DeleteOccurrenceCommentResult,
  OccurrenceComment,
  OccurrenceCommentType,
  UpdateOccurrenceCommentResult,
  UserCreatableCommentType,
} from "./occurrence-comment";

export {
  OCCURRENCE_TIMELINE_DEFAULT_PAGE_SIZE,
  OCCURRENCE_TIMELINE_EVENT_KINDS,
  OCCURRENCE_TIMELINE_STALE_TIME_MS,
  OCCURRENCE_TIMELINE_TITLES,
  formatTimelineTitle,
  isOccurrenceTimelineEventKind,
} from "./occurrence-timeline";
export type {
  GetOccurrenceTimelineResult,
  OccurrenceTimelineEventKind,
  OccurrenceTimelineItem,
  TimelineCursor,
  TimelineCursorPayload,
} from "./occurrence-timeline";

export {
  OCCURRENCE_CONFLICT_ERROR_CODES,
  OCCURRENCE_DECISION_REASON_MAX_LENGTH,
  OCCURRENCE_DECISION_REASON_MIN_LENGTH,
  hasOccurrenceDecision,
  isInterdicaoDecisionBranch,
  isOccurrenceConflictErrorCode,
  isVerEAgirDecisionBranch,
} from "./occurrence-decision";
export type {
  OccurrenceConflictError,
  OccurrenceConflictErrorCode,
  OccurrenceDecision,
  OccurrenceDecisionSnapshot,
  OccurrenceTransitionResult,
  RecordInterdicaoDecisionInput,
  RecordInterdicaoDecisionResult,
  RecordOccurrenceDecisionOccurrenceSnapshot,
  RecordOccurrenceDecisionResult,
  RecordVerEAgirDecisionInput,
  RecordVerEAgirDecisionOccurrenceSnapshot,
  RecordVerEAgirDecisionResult,
  StartEvaluationResult,
} from "./occurrence-decision";

export {
  MDHO_CATEGORY_CODES,
  MDHO_DEVIATION_TYPE_CATEGORY_CODE,
  MDHO_OTHER_OPTION_CODE,
  isMdhoCategoryCode,
} from "./mdho-catalog";
export type {
  MdhoCatalog,
  MdhoCatalogCategory,
  MdhoCatalogOption,
  MdhoCategoryCode,
} from "./mdho-catalog";

export {
  MDHO_ASSESSMENT_STATUSES,
  MDHO_APPROVAL_ERROR_CODES,
  MDHO_COMPLEMENT_MAX_LENGTH,
  MDHO_CONFLICT_ERROR_CODES,
  MDHO_ERROR_CODES,
  MDHO_OTHER_DETAIL_MIN_LENGTH,
  MDHO_RETURN_REASON_MAX_LENGTH,
  MDHO_RETURN_REASON_MIN_LENGTH,
  isMdhoApprovalErrorCode,
  isMdhoAssessmentStatus,
  isMdhoConflictErrorCode,
  isMdhoEditableStatus,
  isMdhoEligible,
  isMdhoErrorCode,
  shouldShowMdhoSection,
} from "./mdho-assessment";
export type {
  ApproveMdhoAssessmentResult,
  MdhoApprovalError,
  MdhoApprovalErrorCode,
  MdhoAssessment,
  MdhoAssessmentSnapshot,
  MdhoAssessmentStatus,
  MdhoConflictError,
  MdhoConflictErrorCode,
  MdhoDomainError,
  MdhoEligibilityOccurrence,
  MdhoErrorCode,
  MdhoOccurrenceSnapshot,
  MdhoSelection,
  MdhoSelectionInput,
  ReturnMdhoAssessmentResult,
  ReturnMdhoInput,
  SaveMdhoDraftInput,
  SaveMdhoDraftResult,
  StartMdhoAssessmentResult,
  SubmitMdhoAssessmentResult,
  SubmitMdhoInput,
} from "./mdho-assessment";

export {
  canApproveMdhoAssessment,
  canReturnMdhoAssessment,
  mapListMdhoPendingApprovalsResult,
  mapMdhoPendingApprovalCursor,
  mapMdhoPendingApprovalItem,
  showHseApprovalQueue,
} from "./mdho-hse-approval";
export type {
  CanApproveMdhoAssessmentInput,
  HseApprovalContext,
  HseApprovalPermissions,
  ListMdhoPendingApprovalsResult,
  MdhoPendingApprovalCursor,
  MdhoPendingApprovalCursorPayload,
  MdhoPendingApprovalItem,
} from "./mdho-hse-approval";

export {
  IMS_REFERENCE_CODE_PATTERN,
  IMS_REFERENCE_ERROR_CODES,
  IMS_UPDATE_REASON_MAX_LENGTH,
  IMS_UPDATE_REASON_MIN_LENGTH,
  isImsReferenceErrorCode,
  isImsRegisterEligible,
  isValidImsReferenceCode,
  canRegisterImsReference,
  canUpdateImsReference,
  shouldShowImsReferenceSection,
} from "./ims-reference";
export type {
  ImsReferenceError,
  ImsReferenceErrorCode,
  ImsReferenceGuardContext,
  ImsReferenceOccurrenceSnapshot,
  ImsReferencePermissions,
  ImsRegisterEligibilityOccurrence,
  RegisterImsReferenceInput,
  RegisterImsReferenceResult,
  UpdateImsReferenceInput,
  UpdateImsReferenceResult,
} from "./ims-reference";

export {
  ACTION_ITEM_ATTACHMENT_MAX_FILE_SIZE_BYTES,
  ACTION_ITEM_ATTACHMENT_MIME_TYPES,
  ACTION_ITEM_ATTACHMENT_UPLOAD_STATUSES,
  ACTION_ITEM_CANCEL_REASON_MAX_LENGTH,
  ACTION_ITEM_CANCEL_REASON_MIN_LENGTH,
  ACTION_ITEM_COMPLETION_DESCRIPTION_MAX_LENGTH,
  ACTION_ITEM_DESCRIPTION_MAX_LENGTH,
  ACTION_ITEM_PRIORITIES,
  ACTION_ITEM_STATUS_SUB_ACTIONS,
  ACTION_ITEM_STATUSES,
  ACTION_ITEM_TITLE_MAX_LENGTH,
  ACTION_ITEM_VALIDATION_NOTE_MAX_LENGTH,
  ACTION_ITEM_VALIDATION_NOTE_MIN_LENGTH,
  ACTION_PLAN_ACTIVE_STATUSES,
  ACTION_PLAN_APPROVAL_ERROR_CODES,
  ACTION_PLAN_DOMAIN_ERROR_CODES,
  ACTION_PLAN_ERROR_CODES,
  ACTION_PLAN_STALE_TIME_MS,
  ACTION_PLAN_STATUSES,
  ACTION_PLAN_SUMMARY_MAX_LENGTH,
  ACTION_PLAN_VALIDATION_OUTCOMES,
  canActAsActionItemResponsible,
  canCompleteActionPlan,
  canCreateActionPlan,
  canManageActionPlan,
  canSubmitActionItem,
  canValidateActionItem,
  isActionItemEditable,
  isActionItemPriority,
  isActionItemStatus,
  isActionPlanActiveStatus,
  isActionPlanApprovalErrorCode,
  isActionPlanDomainErrorCode,
  isActionPlanEditable,
  isActionPlanErrorCode,
  isActionPlanStatus,
  isActionPlanValidationOutcome,
  shouldShowActionPlanSection,
} from "./action-plan";
export type {
  ActionItem,
  ActionItemAttachment,
  ActionItemAttachmentMimeType,
  ActionItemAttachmentUploadStatus,
  ActionItemPriority,
  ActionItemSnapshot,
  ActionItemStatus,
  ActionItemStatusSubAction,
  ActionPlan,
  ActionPlanActiveStatus,
  ActionPlanApprovalError,
  ActionPlanApprovalErrorCode,
  ActionPlanDomainError,
  ActionPlanDomainErrorCode,
  ActionPlanError,
  ActionPlanErrorCode,
  ActionPlanGuardContext,
  ActionPlanPermissions,
  ActionPlanSectionOccurrence,
  ActionPlanSnapshot,
  ActionPlanStatus,
  ActionPlanValidationOutcome,
  CancelActionItemInput,
  CancelActionItemResult,
  CompleteActionPlanResult,
  CreateActionPlanInput,
  CreateActionPlanResult,
  SubmitActionItemInput,
  SubmitActionItemResult,
  UpdateActionPlanInput,
  UpdateActionPlanResult,
  ValidateActionItemInput,
  ValidateActionItemResult,
} from "./action-plan";

export {
  NOTIFICATION_AWARENESS_REQUIRED_EVENT_TYPES,
  NOTIFICATION_DOMAIN_ERROR_CODES,
  NOTIFICATION_ERROR_CODES,
  NOTIFICATION_EVENT_TYPE_ACTION_DUE,
  NOTIFICATION_EVENT_TYPES,
  NOTIFICATION_LIST_DEFAULT_LIMIT,
  NOTIFICATION_LIST_MAX_LIMIT,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_STALE_TIME_MS,
  isNotificationAwarenessRequiredEventType,
  isNotificationDomainErrorCode,
  isNotificationErrorCode,
  isNotificationEventType,
  isNotificationPriority,
  isNotificationUnread,
  mapListMyNotificationsResult,
  mapNotificationListItem,
  requiresNotificationAwareness,
} from "./notification";
export type {
  ConfirmNotificationAwarenessResult,
  ListMyNotificationsInput,
  ListMyNotificationsResult,
  ListMyNotificationsRpcPayload,
  MarkAllNotificationsReadResult,
  MarkNotificationReadResult,
  Notification,
  NotificationAwarenessRequiredEventType,
  NotificationDomainErrorCode,
  NotificationError,
  NotificationErrorCode,
  NotificationEvent,
  NotificationEventType,
  NotificationListItem,
  NotificationPriority,
} from "./notification";

export {
  NotificationRpcConflictError,
  NotificationRpcValidationError,
  assertListMyNotificationsResult,
  assertNotificationRpcDataOrThrow,
  isNotificationRpcConflictError,
  isNotificationRpcValidationError,
} from "./notification-rpc";

export {
  ORGANIZATION_CONTACT_TYPE_LABELS,
  ORGANIZATION_CONTACT_TYPE_MANAGING_COMPANY_SUPERVISOR,
  ORGANIZATION_CONTACT_TYPES,
  canManageOrganizationContacts,
  isOrganizationContactType,
  isOrganizationContactTypeExtended,
  mapOrganizationContact,
} from "./organization-contact";
export type {
  CreateOrganizationContactInput,
  OrganizationContact,
  OrganizationContactGuardContext,
  OrganizationContactInsert,
  OrganizationContactListFilters,
  OrganizationContactPermissions,
  OrganizationContactRow,
  OrganizationContactType,
  OrganizationContactTypeExtended,
  OrganizationContactUpdate,
  UpdateOrganizationContactInput,
} from "./organization-contact";

export { assertRpcSuccess, getRpcErrorMessage, parseRpcEnvelope } from "./rpc-envelope";
export type { RpcEnvelope, RpcErrorPayload } from "./rpc-envelope";

export {
  DASHBOARD_DUE_SOON_DAYS_DEFAULT,
  DASHBOARD_TERMINAL_OCCURRENCE_STATUSES,
  DASHBOARD_PENDING_EVALUATION_STATUSES,
  DASHBOARD_ACTIVE_INTERDICTION_STATUSES,
  DASHBOARD_AWAITING_VALIDATION_STATUS,
  DASHBOARD_OPEN_ACTION_ITEM_STATUSES,
  DASHBOARD_CLOSED_ACTION_ITEM_STATUSES,
  DASHBOARD_OPEN_ACTION_PLAN_STATUSES,
  DASHBOARD_MDHO_PENDING_APPROVAL_STATUS,
  DASHBOARD_OCCURRENCE_STATUS_FAMILIES,
  DASHBOARD_OCCURRENCE_STATUS_FAMILY_LABELS,
  DASHBOARD_OCCURRENCE_STATUSES_BY_FAMILY,
  getOccurrenceStatusFamily,
  isActiveOccurrence,
  isPendingEvaluationOccurrence,
  isActiveInterdictionOccurrence,
  isAwaitingValidationOccurrence,
  isOpenActionItem,
  isMyPendingActionItem,
  isOverdueActionItem,
  isDueSoonActionItem,
  isOpenActionPlan,
  aggregateOccurrencesByStatusFamily,
  computeAverageMinutes,
  computeActionCompletionRate,
  isWithinPeriod,
  matchesOrganizationContactScope,
  isOccurrenceInAnyContactScope,
  countNewOccurrencesInPeriod,
  computeAvgEvaluationTimeMinutes,
  computeAvgReleaseTimeMinutes,
  computeActionCompletionRateForPeriod,
  countOccurrencesByStatusFamily,
  countActiveOccurrences,
  countPendingEvaluationOccurrences,
  countActiveInterdictionOccurrences,
  countAwaitingValidationOccurrences,
} from "./dashboard-formulas";
export type {
  DashboardOccurrenceStatusFamily,
  OrganizationContactScopeRow,
  OccurrenceScopeRow,
} from "./dashboard-formulas";

export {
  DASHBOARD_STALE_TIME_MS,
  DASHBOARD_RECENT_OCCURRENCES_LIMIT,
  DASHBOARD_METRIC_CATALOG,
  canAccessActionPlanMetrics,
  canAccessMdhoPendingApproval,
  canAccessOccurrenceMetrics,
  canAccessOperationalMetrics,
  buildDashboardAccessContext,
} from "./dashboard-metrics";
export type {
  DashboardMetricScope,
  DashboardMetricUnit,
  DashboardMetricDefinition,
  DashboardMetricKey,
  DashboardPeriodFilter,
  DashboardKpiFilters,
  DashboardPersonalKpis,
  DashboardOperationalKpis,
  DashboardManagerialKpis,
  DashboardKpis,
  DashboardDistributionByStatusFamily,
  DashboardDistributionItem,
  DashboardActionItemAttentionItem,
  DashboardActionItemsAttention,
  DashboardRecentOccurrenceItem,
  DashboardAccessContext,
  BuildDashboardAccessContextInput,
  DashboardKpisRpcPayload,
  MyActionItemsSummary,
  MyAwarenessSummary,
  OccurrenceKpis,
  FlowMetrics,
} from "./dashboard-metrics";

export {
  DASHBOARD_CLIENT_FALLBACK_DEADLINE,
  DashboardKpisRpcError,
  buildDashboardKpisRpcArgs,
  extractDashboardDistributionFromRpc,
  isDashboardClientFallbackAllowed,
  isDashboardKpisRpcUnavailableError,
  mapDashboardKpisRpcPayload,
  toDashboardKpis,
} from "./dashboard-rpc";
export type {
  DashboardDistributionFromRpc,
  DashboardKpisRpcArgs,
  DashboardManagerialKpisRpc,
} from "./dashboard-rpc";

export {
  REPORT_TYPES,
  REPORT_EXPORT_FORMATS,
  REPORT_SORT_DIRECTIONS,
  REPORT_PAGINATION_DEFAULT_LIMIT,
  REPORT_PAGINATION_MAX_LIMIT,
  REPORT_EXPORT_MAX_ROWS,
  OCCURRENCE_REPORT_SORT_FIELDS,
  ACTION_ITEM_REPORT_SORT_FIELDS,
  AWARENESS_REPORT_SORT_FIELDS,
  REPORT_RPC_ERROR_CODES,
  isReportType,
  isReportExportFormat,
  isReportSortDirection,
  isOccurrenceReportSortField,
  isActionItemReportSortField,
  isAwarenessReportSortField,
  buildListOccurrencesReportRpcArgs,
  buildListActionItemsReportRpcArgs,
  buildListAwarenessReportRpcArgs,
  mapOccurrenceReportRow,
  mapActionItemReportRow,
  mapAwarenessReportRow,
  mapListOccurrencesReportResult,
  mapListActionItemsReportResult,
  mapListAwarenessReportResult,
  parseReportRpcErrorCode,
  getReportRpcSafeMessage,
  ReportRpcError,
  isReportRpcUnavailableError,
  computeOccurrenceReportSummary,
  computeActionItemReportSummary,
  computeAwarenessReportSummary,
  buildLogReportExportRpcArgs,
} from "./report";
export type {
  ReportType,
  ReportExportFormat,
  ReportSortDirection,
  OccurrenceReportSortField,
  ActionItemReportSortField,
  AwarenessReportSortField,
  ReportSort,
  OccurrenceReportSort,
  ActionItemReportSort,
  AwarenessReportSort,
  ReportCursor,
  ReportPagination,
  OccurrenceReportFilters,
  ActionItemReportFilters,
  AwarenessReportFilters,
  OccurrenceReportRow,
  ActionItemReportRow,
  AwarenessReportRow,
  ListOccurrencesReportResult,
  ListActionItemsReportResult,
  ListAwarenessReportResult,
  ListOccurrencesReportRpcArgs,
  ListActionItemsReportRpcArgs,
  ListAwarenessReportRpcArgs,
  ReportRpcErrorCode,
  OccurrenceReportSummary,
  ActionItemReportSummary,
  AwarenessReportSummary,
  LogReportExportInput,
  LogReportExportRpcArgs,
} from "./report";
