export const HSE_APPROVAL_COPY = {
  queueTitle: "Aprovação HSE",
  queueSubtitle: "Aguardando sua aprovação",
  reviewSectionTitle: "Aprovação HSE",
  reviewStatus: "Aguardando aprovação HSE",
  emptyTitle: "Nenhuma avaliação aguardando sua aprovação",
  emptyBody: "Quando um Supervisor enviar um MDHO, ele aparecerá aqui.",
  forbiddenQueue: "Você não tem permissão para a fila de Aprovação HSE.",
  submittedByLabel: "Enviado por",
  submittedAtLabel: "Em",
  approveCta: "Aprovar MDHO",
  returnCta: "Devolver MDHO",
  approveDialogTitle: "Aprovar Avaliação Técnica (MDHO)?",
  approveDialogBody:
    "A avaliação ficará imutável. A ocorrência seguirá para aguardar o registro da referência IMS.",
  approveDialogAction: "Aprovar MDHO",
  returnDialogTitle: "Devolver Avaliação Técnica (MDHO)?",
  returnReasonLabel: "Motivo da devolução",
  returnReasonHelper: "Mínimo 10 caracteres",
  returnDialogAction: "Devolver MDHO",
  cancel: "Cancelar",
  offlineToast: "Sem conexão — ação não enviada",
  selfApprovalInfo: "Quem enviou o MDHO não pode aprová-lo.",
  conflictMessage: "Esta avaliação foi atualizada. Atualize para continuar.",
  conflictRefresh: "Atualizar",
  returnReasonTooShort: "Informe um motivo com pelo menos 10 caracteres.",
  returnReasonTooLong: "O motivo deve ter no máximo 4000 caracteres.",
  approving: "Aprovando…",
  returning: "Devolvendo…",
  pendingBadge: "Pendente",
  queueLoadError: "Não foi possível carregar a fila de Aprovação HSE.",
} as const;
