export const IMS_REFERENCE_COPY = {
  sectionTitle: "Referência IMS",
  sectionLabel: "REFERÊNCIA IMS",
  codeLabel: "Código IMS",
  helper: "Informe o código gerado no sistema IMS da Hydro. O SafeStop não consulta o IMS.",
  placeholder: "BAA-26-0001",
  formatHint: "Formato: BAA-XX-0000",
  registerCta: "Registrar referência IMS",
  confirmTitle: "Registrar referência IMS?",
  confirmBody:
    "A ocorrência passará para Em Tratativa. O SafeStop não valida este código no sistema IMS.",
  confirmAction: "Registrar referência IMS",
  successRegister: "Código registrado — ocorrência em tratativa",
  editCta: "Corrigir referência",
  formatError: "Use o formato BAA-XX-0000 (ex.: BAA-26-0001).",
  editTitle: "Corrigir referência IMS",
  newCodeLabel: "Novo código",
  reasonLabel: "Motivo da correção",
  reasonHelper: "Mínimo 10 caracteres",
  saveEditCta: "Salvar correção",
  cancel: "Cancelar",
  reasonTooShort: "Informe um motivo com pelo menos 10 caracteres.",
  reasonTooLong: "O motivo deve ter no máximo 4000 caracteres.",
  offlineToast: "Sem conexão — ação não enviada",
  conflictMessage: "Esta ocorrência foi atualizada. Atualize para continuar.",
  conflictRefresh: "Atualizar",
  searchLabel: "Código IMS",
  searchPlaceholder: "BAA-26-0001",
  searchEmpty: "Nenhuma ocorrência com este código IMS.",
  registeredByLabel: "Registrado por",
  updatedByLabel: "Atualizado por",
  atLabel: "Em",
  currentCodeLabel: "Código atual",
  codeDisplayLabel: "Código",
  registering: "Registrando…",
  saving: "Salvando…",
  inTreatmentBadge: "Em Tratativa",
} as const;
